[2022-05-07 08:34:08,382: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-07 08:34:10,386: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-07 08:34:14,391: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-07 08:38:05,273: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-07 08:38:07,276: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-07 08:38:11,281: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-07 08:38:21,944: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-07 08:38:23,956: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-07 08:38:37,529: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-07 08:38:39,533: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-07 08:38:48,345: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-07 08:38:50,349: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-07 08:38:54,354: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-07 08:39:00,360: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-05-07 08:39:08,369: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-05-07 08:39:18,379: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2022-05-07 08:39:30,391: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2022-05-07 08:39:44,403: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2022-05-07 08:40:00,418: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2022-05-13 12:45:23,386: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-13 12:45:25,391: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-13 12:45:29,396: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-13 12:45:35,403: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-05-13 12:45:43,410: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-05-13 12:45:53,419: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2022-05-13 12:46:05,432: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2022-05-13 12:46:19,447: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2022-05-13 12:46:35,459: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2022-05-13 12:46:53,476: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2022-05-13 12:47:13,494: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2022-05-13 12:47:35,514: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2022-05-13 12:47:59,534: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2022-05-13 12:48:25,557: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2022-05-13 12:48:53,580: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2022-05-13 12:49:23,607: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:49:55,637: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:50:27,667: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:50:59,695: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:51:31,724: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:52:03,750: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:52:35,778: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:53:07,807: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:53:39,833: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:54:11,867: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:54:43,895: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:55:15,931: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:55:47,960: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:56:19,990: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:56:52,017: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-13 12:57:24,043: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:24:08,079: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-16 16:24:10,083: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-16 16:24:14,088: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-16 16:24:20,093: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-05-16 16:24:28,102: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-05-16 16:24:38,112: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2022-05-16 16:24:50,124: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2022-05-16 16:25:04,136: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2022-05-16 16:25:20,150: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2022-05-16 16:25:38,167: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2022-05-16 16:25:58,183: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2022-05-16 16:26:20,203: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2022-05-16 16:26:44,224: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2022-05-16 16:27:10,248: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2022-05-16 16:27:38,273: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2022-05-16 16:28:08,296: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:28:40,323: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:29:12,348: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:29:44,373: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:30:16,401: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:30:48,427: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:31:20,453: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:31:52,480: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:32:24,509: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:32:56,533: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:33:28,561: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:34:00,588: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:34:32,611: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:35:04,636: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:35:36,665: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:36:08,693: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:36:40,719: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:37:12,747: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:37:44,774: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:38:16,800: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:38:48,828: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:39:20,855: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:39:52,885: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:40:24,911: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:40:56,938: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:41:28,971: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:42:00,998: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:42:33,027: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:43:05,056: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:43:37,084: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:44:09,113: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:44:41,140: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:45:13,166: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:45:45,194: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:46:17,223: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:46:49,251: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:47:21,281: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:47:53,310: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:48:25,337: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:48:57,366: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:49:29,397: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:50:01,426: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:50:33,458: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:51:05,485: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:51:37,511: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:52:09,536: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:52:41,565: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:53:13,593: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:53:45,617: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:54:17,644: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:54:49,669: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:55:21,698: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:55:53,724: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:56:25,753: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:56:57,779: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:57:29,807: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:58:01,836: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:58:33,865: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:59:05,893: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 16:59:37,925: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:00:09,957: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:00:41,986: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:01:14,011: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:01:46,040: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:02:18,067: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:02:50,096: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:03:22,124: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:03:54,148: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:04:26,174: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:04:58,200: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:05:30,224: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:06:02,249: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:06:34,276: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:07:06,304: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:07:38,329: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:08:10,358: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:08:42,386: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:09:14,414: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:09:46,443: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:10:18,470: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:10:50,497: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:11:22,525: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:11:54,553: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:12:26,579: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:12:58,606: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 17:13:30,634: CRITICAL/MainProcess] Unrecoverable error: OperationalError('Error 111 connecting to localhost:6379. Connection refused.')
Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 925, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 614, in connect
    sock = self.retry.call_with_retry(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 615, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 680, in _connect
    raise err
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 668, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
    yield
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 949, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 927, in create_channel
    channel = self.Channel(connection)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 737, in __init__
    self.client.ping()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/commands/core.py", line 1053, in ping
    return self.execute_command("PING", **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/client.py", line 1215, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 1386, in get_connection
    connection.connect()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 428, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 434, in connection_for_read
    return self.ensure_connected(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 460, in ensure_connected
    conn = conn.ensure_connection(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 381, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 432, in _ensure_connection
    with ctx():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 111 connecting to localhost:6379. Connection refused.
[2022-05-16 18:06:07,216: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-16 18:06:09,220: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-16 18:06:13,224: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-16 18:06:19,231: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-05-16 18:06:27,238: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-05-16 18:06:37,249: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2022-05-16 18:06:49,259: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2022-05-16 18:07:03,271: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2022-05-16 18:07:19,285: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2022-05-16 18:07:37,302: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2022-05-16 18:07:57,320: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2022-05-16 18:08:19,338: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2022-05-16 18:08:43,360: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2022-05-16 18:09:09,381: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2022-05-16 18:09:37,405: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2022-05-16 18:10:07,432: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:10:39,459: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:11:11,484: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:11:43,511: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:12:15,539: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:12:47,567: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:13:19,593: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:13:51,622: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:14:23,649: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:14:55,676: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:15:27,703: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:15:59,728: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:16:31,753: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:17:03,780: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:17:35,808: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:18:07,835: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:18:39,864: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:19:11,888: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:19:43,916: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:20:15,940: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:20:47,969: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:21:19,997: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:21:52,025: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:22:24,052: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:22:56,081: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:23:28,107: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:24:00,135: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:24:32,167: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:25:04,195: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:25:36,222: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:26:08,249: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:26:40,277: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:27:12,306: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:27:44,336: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:28:16,365: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:28:48,392: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:29:20,419: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:29:52,447: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:30:24,474: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:30:56,506: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:31:28,537: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:32:00,568: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:32:32,599: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:33:04,630: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:33:36,658: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:34:08,686: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:34:40,716: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:35:12,745: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:35:44,771: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:36:16,801: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:36:48,831: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:37:20,861: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:37:52,893: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:38:24,924: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:38:56,954: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:39:28,985: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:40:01,016: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:40:33,047: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:41:05,078: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:41:37,109: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:42:09,136: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:42:41,166: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:43:13,193: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:43:45,222: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:44:17,248: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:44:49,278: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:45:21,309: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:45:53,337: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:46:25,366: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:46:57,394: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:47:29,422: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:48:01,450: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:48:33,478: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:49:05,509: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:49:37,536: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:50:09,562: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:50:41,590: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:51:13,619: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:51:45,648: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:52:17,679: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:52:49,708: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:53:21,734: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:53:53,763: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:54:25,791: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:54:57,819: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 18:55:29,848: CRITICAL/MainProcess] Unrecoverable error: OperationalError('Error 111 connecting to localhost:6379. Connection refused.')
Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 925, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 614, in connect
    sock = self.retry.call_with_retry(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/retry.py", line 45, in call_with_retry
    return do()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 615, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 680, in _connect
    raise err
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 668, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 446, in _reraise_as_library_errors
    yield
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 433, in _ensure_connection
    return retry_over_time(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/utils/functional.py", line 312, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 877, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 812, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 949, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/virtual/base.py", line 927, in create_channel
    channel = self.Channel(connection)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/transport/redis.py", line 737, in __init__
    self.client.ping()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/commands/core.py", line 1053, in ping
    return self.execute_command("PING", **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/client.py", line 1215, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 1386, in get_connection
    connection.connect()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 332, in start
    blueprint.start(self)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/connection.py", line 21, in start
    c.connection = c.connect()
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 428, in connect
    conn = self.connection_for_read(heartbeat=self.amqheartbeat)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 434, in connection_for_read
    return self.ensure_connected(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 460, in ensure_connected
    conn = conn.ensure_connection(
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 381, in ensure_connection
    self._ensure_connection(*args, **kwargs)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 432, in _ensure_connection
    with ctx():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/nicourrrn/.cache/pypoetry/virtualenvs/course-work-spI8ysbz-py3.10/lib/python3.10/site-packages/kombu/connection.py", line 450, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 111 connecting to localhost:6379. Connection refused.
[2022-05-16 19:53:15,541: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-05-16 19:53:17,544: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[2022-05-16 19:53:21,549: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[2022-05-16 19:53:27,555: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[2022-05-16 19:53:35,563: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[2022-05-16 19:53:45,573: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[2022-05-16 19:53:57,586: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[2022-05-16 19:54:11,599: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[2022-05-16 19:54:27,614: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[2022-05-16 19:54:45,629: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 20.00 seconds... (10/100)

[2022-05-16 19:55:05,648: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 22.00 seconds... (11/100)

[2022-05-16 19:55:27,669: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 24.00 seconds... (12/100)

[2022-05-16 19:55:51,689: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 26.00 seconds... (13/100)

[2022-05-16 19:56:17,712: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 28.00 seconds... (14/100)

[2022-05-16 19:56:45,738: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 30.00 seconds... (15/100)

[2022-05-16 19:57:15,766: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 19:57:47,796: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 19:58:19,821: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 19:58:51,849: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 19:59:23,879: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 19:59:55,907: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:00:27,936: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:00:59,965: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:01:31,993: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:02:04,022: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:02:36,049: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:03:08,079: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:03:40,109: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:04:12,138: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:04:44,170: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:05:16,198: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:05:48,226: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:06:20,253: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

[2022-05-16 20:06:52,283: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379//: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 32.00 seconds... (16/100)

